name: anfibius_uwu
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI y funcionalidad básica
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.2.4

  # Networking & Data
  web_socket_channel: ^3.0.3
  http: ^1.5.0
  json_annotation: ^4.9.0

  # Impresión
  flutter_esc_pos_utils: ^1.0.1
  flutter_pos_printer_platform_image_3: ^1.2.4

  # Hardware & Periféricos (Biométrico + NFC)
  device_manager: ^0.0.7
  ffi: ^2.1.0
  flutter_nfc_kit: ^3.4.1
  dart_pcsc: ^2.0.2

  # Almacenamiento local
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # Notificaciones (Manteniendo versiones estables de la rama NFC)
  flutter_local_notifications: ^19.2.1
  flutter_local_notifications_windows: ^1.0.2
  timezone: ^0.10.1

  # Android - Mantener activo en background
  flutter_foreground_task: ^8.0.0
  wakelock_plus: ^1.2.0
  permission_handler: ^11.3.1

  # Desktop - Gestión de ventanas
  window_manager: ^0.5.1
  desktop_multi_window: ^0.2.1
  launch_at_startup: ^0.5.1
  tray_manager: ^0.5.0

  # Utilidades
  package_info_plus: ^8.3.0
  intl: ^0.19.0
  share_plus: ^7.2.2
  image: any
  logging: ^1.3.0
  
  # Splash screen
  flutter_native_splash: 2.4.4

  # Encriptación
  crypto: ^3.0.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  
  # Necesarios para compilar json_annotation 
  build_runner: ^2.10.0
  json_serializable: ^6.11.1
  
  # Necesario para el empaquetado en Windows
  msix: ^3.16.7

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/anficon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/anficon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.ico"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/anficon.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/icon/anficon.png"
    - "assets/icon/icon.png"
    - "assets/icon/icon.ico"
    - "assets/icon/app_icon.ico"
    - "assets/icon/OIP.png"
    - "assets/icon/splash.png"
    - "assets/icon/logo.png"
    - "assets/icon/logo.svg"

msix_config:
  display_name: AnfibiusConnect
  publisher_display_name: Corp. Anfibius
  identity_name: Corp.Anfibius.AnfibiusConnect
  msix_version: 2.0.2.0
  logo_path: assets/icon/anficon.png
  capabilities: 'internetClient,removableStorage'
  store: true
  publisher: CN=EE5F7164-63B8-47BB-A93B-7709F27A1A24
  output_name: AnfibiusConnect

flutter_native_splash:
  color: "#f4fbed"
  color_dark: "#121212"
  image: assets/icon/splash.png
  fullscreen: true 
  
  android_12:
    image: assets/icon/splash.png
    color: "#f4fbed"
    color_dark: "#121212"